### ISSUE TITLE
"Invisible" Weapons Selections

### ISSUE THREAD

**Issue by Lord-Falkenrath** [BSData/horus-heresy#1903] opened 2021-04-06 03:13 UTC
Apologies for my second thread today, but given the widespread nature of this problem I figured I'd put all the offenders in one post, organized by Legion and Unit. The issue itself is selecting a given piece of wargear and the stats/abilities of said wargear not appearing, even though the points cost is appropriately increased and the item name is often (but not always) referenced in the appropriate keywords/wargear section.

Note that this list does not include any Lord of War options, I do not know if any of those options suffer from similar issues. Again, I apologize for potential bad formatting and the lack of tags, I am new here.

**All Legions:**

- [x] Terminator Command Squad: Twin Lightning Claws (but not single lightning claws), Grenade Harness (on Standard Bearer)
- [x] Centurion in Terminator Armor(Any centurion, any pattern): Twin Lightning Claws (but not single claws)
- [x] Forge Lord Centurion: (Consul Box) Master-Crafted Bolter, Plasma Pistol
- [x] Praetor in Terminator Armor(Any pattern): Twin Lightning Claws (but not single claws)
- [ ] Knight-Errant: Librarian and Psychic Mastery Level upgrades do not specify disciplines, Jump Pack does not confer Jump Infantry type and rules.
- [x] Assault Squad: Sergeant options only Hand Flamer and Twin Lightning Claws
- [x] Breacher Siege Squad: Sergeant options only Single Lightning Claw(Exchange Bolter/Bolt Pistol box only), Thunder Hammer
- [x] Reconnaissance Squad: Melta bombs. Sergeant options (Bolt Pistol Box) Chainsword/Combat blade, Power Fist, Single Lightning Claw; (Bolter Box) Chainsword/Combat Blade, Hand Flamer, Power Fist, Single Lightning Claw
- [x] Tactical Squad: Extra Chainswords/Combat Blades grants Chainaxe item to non-World Eaters.
- [x] All Force Weapons: Force Mauls display Force Sword stats, and vice versa.

**Dark Angels:**

- [x] Deathwing Terminator Companions: Twin Lightning Claws (but not single lightning claws)
- [ ] ~Scion of the Ironwing Upgrade: Not missing, but worded incorrectly. As written it has the unit "treat results of crew shaken as crew stunned", when it is meant to be "treat results of crew stunned as crew shaken".~

**Emperor's Children:**

- [x] Palatine Blades: Jump Packs, Sgt Meltabombs.
- [ ] ~Loyalists can take Sonic Shriekers.~

**Iron Warriors:**

- [x] Tyrant Siege Terminators: Chainfist
- [x] Iron Havocs: Sgt Meltabombs

**Space Wolves:**

- [x] Priest of Fenris(Both types): Aether-Rune Armor does not increase wounds by +1 in statline

**Imperial Fists:**

- [x] Templar Brethren: Default Bolt Pistol+Power Sword, Combat shields, Plasma Pistol, Melta Bombs. Sgt Only Power Axe/Fist/Maul, Thunder Hammer.
- [x] Phalanx Warder Squad: Power Axe, Flamer, Meltagun, Plasma gun, Thunderhammer (none missing on Sgt)

**Night Lords:**

- [x] Night Raptor Squad: Sgt only Hand Flamer, Plasma Pistol

**Iron Hands:**

- [x] Gorgon Terminators: Pair of Lightning Claws, Chainfist, Single Lightning Claw, Power Fist, Heavy Flamer.

**World Eaters:**

- [x] Rampager Squads(Both Fast Attack and Elite): Jump Packs, Heavy Chainsword.
- [x] Red Butchers: Second Power Axe, Pair of Lightning Claws. Sgt only chainfist, power fist, thunderhammer, pair of lightning claws, second power axe.

**Ultramarines:**

- [x] Invictus Suzurain: Legatine Axe is missing the Severing Cut ability, Plasma Pistol.
- [x] Locutarus Strike Squad: Sgt only Hand Flamer, Plasma Pistol, Power Axe, Power Fist, Single Lightning Claw, Combat Shield, Meltabombs
- [x] Fulmentarus Terminators: Reaper Autocannons, Power Axe/Fist/Sword.

 

**Death Guard:**

- [x] Deathshroud Terminators: Meltabombs
- [x] Grave Warden Terminators: Chainfist, Heavy Flamer w/ Chem Munitions. Sgt only Combi-weapon.

**Sons of Horus:**

- [x] Reaver Squads: Jump Packs, Meltabombs

**Word Bearers:**

- [x] Ashen Circle: Power Axe, Meltabombs.
- [x] Gal Vorbak: All weapon options, including default weapons.

**Salamanders:**

- [x] Pyroclast Squad: Meltabombs. Sgt only power fist.
- [x] Firedrake Terminators: Sgt only Chainfist, Master-crafted Thunder Hammer, Power Fist, Combi-Flamer/Melta.

**Raven Guard:**

- [x] Dark Fury Assault Squad: Meltabombs
- [x] Mor Deythan: Artificer Armor

**Comment by Mayegelt** [comment] 2021-04-06 08:19
Thanks again for the great list. I'm working through some of them now...
Might end up struggling with "Knight-Errant: Librarian Jump Pack does not confer Jump Infantry type and rules." as I'm sure there are some unintended consequences in moving the current one up from the Cat file to GST. So will likely take a bit longer to do. But I can make a separate issue for that particular one. A partial fix is in to give them the rules. But I think I'm going to have to seek some help to move a ton of entry stuff across with a parser, rather than the data editor.

In addition the Knight-Errant: Librarian and Psychic Mastery Level upgrades do not specify disciplines. Because it uses all normal disciplines this is treated the same as a Librarian. Whilst the Nullificator and Esoterist are treated differently due to the addition of the abnormal disciplines they can take which are an exception to the normal rules.

**Comment by CodicierDio** [comment] 2021-04-08 01:11
Multiple Crassus-type and Macharius-type vehicles have missing sponson weapon options. Please also check the functionality of side armour upgrades.

**Comment by Mayegelt** [comment] 2021-04-11 14:10
Hopefully will get to this soon. Just had another quick glance over and saw the Ironwing one. The wording is correct on it.
The buff is an offensive buff for your units shooting at enemy vehicles. So upgrading a shaken into a stunned result.
Not a defensive buff like extra armour reducing a stunned to a shaken.

**Comment by Lord-Falkenrath** [comment] 2021-04-11 15:40
Ah, I must've misread the Ironwing rule then. That's 100% my bad.

**Comment by Mayegelt** [comment] 2021-04-13 21:14
Done a bit more. Looks like Shekmet had some issues with lacking weapon rules as well. I've put them in, but think I might replace the selection entries to save some file space. But might leave that for when I try to do a more global check on all units to make sure their isn't as much replication of data.

**Comment by Mayegelt** [comment] 2021-04-13 21:31
**Emperor's Children:**
Loyalists can take Sonic Shriekers.

Are they not meant to be able to, or are you not getting the option to take them in BS?
Because from what I can see there doesn't seem to be a restriction of loyal or traitor on BS or in the Legions book. Though some units are only allowed to take them if you take the are using the 3rd company elite RoW which is Traitor restricted.
Any examples of where this isn't working as intended are useful. As I can't seem to see it as not working right ATM. But it may just be I'm tired.

**Comment by Lord-Falkenrath** [comment] 2021-04-15 17:45
@Mayegelt 
Upon review of the rulebooks and FAQ, I cannot find the rule where it states that Loyalist EC can take the shriekers. This issue may be safely ignored, as Loyalists currently can take them in BS. I am not sure where I first saw that, but I cannot find it again and it seems intended for loyalists to have access to them.

**Comment by Mayegelt** [comment] 2021-04-15 17:48
> @Mayegelt
> Upon review of the rulebooks and FAQ, I cannot find the rule where it states that Loyalist EC can take the shriekers. This issue may be safely ignored, as Loyalists currently can take them in BS. I am not sure where I first saw that, but I cannot find it again and it seems intended for loyalists to have access to them.

Might be you confused it with Kakophoni who are traitor only.

**Comment by Lord-Falkenrath** [comment] 2021-04-15 17:50
That is entirely possible. Regardless, I raised that issue in error, my apologies.

**Comment by Mayegelt** [comment] 2021-04-28 08:27
Ok looks like all the boxes I can do are ticked. So hopefully should go live soon.

**Closed** 2021-05-01 22:42 UTC
Labels: Bug - Choice, Bug - Cost, Done but not live yet
