### ISSUE TITLE
LoWs Missing - CAL

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#699] opened 2017-02-03 14:10 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** cannot add any of the baneblade variants from the low as they are not there

**Comment by alphalas** [comment] 2017-02-03 15:43
first half was dupe of #483

**Comment by alphalas** [comment] 2017-02-03 15:48
second half dupe of #528

**Closed by alphalas** 2017-02-03 15:48 UTC
Labels: enhancement, Legion
