### ISSUE TITLE
Corrupted data.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#432] opened 2016-09-05 02:38 UTC
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Hello there dear support team.problem is that i cant create a new roster using horus heresy gstz. It says that i have to choose both, force and catalogue but i can choose only the catalogue, but the.forces drop down menu doesnt work and i cannot.create therefor a new.roster. maybe im using it.wrong but  dont think so.

**Comment by capitaladot** [comment] 2016-09-05 03:21
"Delete All Data" and try again.

**Comment by capitaladot** [comment] 2016-10-10 17:45
Was leaving this open because it seems to be happening repeatedly.

**Comment by Millicant** [comment] 2016-10-10 17:53
Ah, gotcha.  Wonder why?

**Comment by capitaladot** [comment] 2016-10-10 17:55
No good explanation... I haven't mis-released a borked file in quite a
while.

**Comment by Millicant** [comment] 2016-10-10 17:58
No, I don't think that's the cause.  Good idea to keep an eye on it - might be hard to pin down though.

**Comment by Millicant** [comment] 2016-11-06 21:54
Think we can close this now - I'm sure there's plenty of other new t hings to keep up with...

**Closed by Millicant** 2016-11-06 21:54 UTC
Labels: bug
