### ISSUE TITLE
Liberation Force ROW asking for Solar Aux/Militia selection after already having an allied detachment of Solar Aux

### ISSUE THREAD

**Issue by MysticGamer58** [BSData/horus-heresy#3132] opened 2024-02-27 01:58 UTC
As the title says, I get an error whenever I have the RG Liberation Force ROW selected with a RG Primary Detachment and a Solar Aux allied detachment. I get two identical errors that say "army name here must have 1 more selections from Solar Auxilia or Imperials Militia (minimum 1)
![LF test](https://github.com/BSData/horus-heresy/assets/161401406/f3914318-0e24-48d6-b7e0-457ff4d5584a)

 - OS: IOS and Windows 11
 - Battlescribe
 - Horus Heresy v18.2.0
 - 02/09/2024

**Comment by nstephenh** [comment] 2024-02-27 12:37
I think this is likely a duplicate of the issue we saw with emperor's children, and *should* be fixed in the next release. https://github.com/BSData/horus-heresy/issues/3119

But if you'd like to test it you can download the master branch.

**Comment by nstephenh** [comment] 2024-02-27 15:10
@MysticGamer58 this should have just been published in the last release, if you can double check that it's fixed/working as intended.

**Closed** 2024-02-27 15:10 UTC
Labels: bug
