### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Space Wolves.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3219] opened 2024-05-29 20:42 UTC
**File:** 2022 - LA - Space Wolves.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Space Wolf Jarl has disappeared as an option for all types of Praetor.

**Comment by nstephenh** [comment] 2024-05-29 21:04
Duplicate of #3216

**Closed by nstephenh** 2024-05-29 21:04 UTC
