### ISSUE TITLE
[Anon] Bug report: (HH) Legiones Astartes - Crusade Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#748] opened 2017-02-17 16:44 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** When selecting weapon options for characters, an entry that says "Hand Flamer (blood angels)" pops up as well as the others.
I'm not sure if this is a bug for all legions or just word bearers.

**Comment by zopha** [comment] 2017-02-17 17:43
Duplicate of #752

**Closed by zopha** 2017-02-17 17:43 UTC
Labels: bug, duplicate
