### ISSUE TITLE
Legiones Astartes General Bugs

### ISSUE THREAD

**Issue by Tomakokamikaze** [BSData/horus-heresy#1607] opened 2019-11-19 13:17 UTC
*Bugs:

Two handed/Heavy Chainsword -> no Weapon Profile shown

Assault Squads -> coming with power axes as additional gear as default

Legion Rapier Battery -> not showing Quad Heavy Bolter weapon profile

Pride of The Legion Rite of War -> Ebon Keshig not counting as compulsory troop choices

Blackshield Marauder Squads -> always showing in troop choices

Alpha Legion Headhunter Kill Teams -> should lose their Infiltrate when they pick a rhino as a dedicated transport (unless this rule was changed somewhere)

Alpha Legion Rewards of Treason -> General update and remove rules that are Legiones Astartes (X) and use Legiones Astartes (Alpha Legion)

*Suggested Improvements:

Almost all Units -> Should already come with the Chainsword/Combat Blades that are present in its standard profile

White Scars Kyzagan Assault Land Speeder -> I believe we can drop the "White Scars" and Just call it "Kyzagan Assault Land Speeder"

The Ebon Keshig -> missing Max Grenade Harness & Max Power Glaive
-> shouldn't come with a grenade harness as default
->Should come with 5 power glaives as default

Headhunter Killteams ->  Headhunters and Sargent should come with the combi weapon > combi bolter with banestrike rounds chosen as default

**Comment by Mayegelt** [comment] 2019-11-19 15:57
I'll have a check on these hopefully in the next week or 2. Got issue with my eye currently, so hard to do a lot though.

However
"Pride of The Legion Rite of War -> Ebon Keshig not counting as compulsory troop choices"
The unit has the Support Unit rule. So can't be compulsory, regardless of RoW or FoC.

"White Scars Kyzagan Assault Land Speeder -> I believe we can drop the "White Scars" and Just call it "Kyzagan Assault Land Speeder""
It could be dropped, but it's fine as it is imoo as it's the unit entry name in the book, like "The Kakophoni of the Emperor's Children" is listed like that, because it's the unit name in the book.

**Comment by Tomakokamikaze** [comment] 2019-11-19 16:58
Also, would be nice to have warlord trait selection options, but that is a bigger job

**Comment by Mayegelt** [comment] 2019-11-19 18:15
It's not a major issue to have warlord traits as a thing. I couldn't decide how to put it in though.
I think in the files they are all already there. But it's just an issue of how to put it in. As in a new selection category like fast attack / elite or add a box to each character that can become warlord as warlord with a 0-1 limiter. But even then you get an issue of some characters MUST be leader. Or must be unless X.

**Comment by Tomakokamikaze** [comment] 2019-11-19 19:09
i currently manage the Battlefleet gothic Github, so I am no stranger to battlescribe inner workings, even if Im not very good at it.

I think we could put it like in the 8ed 40k battlescribe.

**Comment by Tomakokamikaze** [comment] 2019-11-20 14:57
Also Headhunter Prime Max power daggers to buy should be one (as he already has one as default and can buy one more)

**Comment by Mayegelt** [comment] 2019-11-23 14:49
Two handed/Heavy Chainsword -> no Weapon Profile shown
(Added the Two-Handed rule to the only missing Heavy Chainsword entry)

Assault Squads -> coming with poweraxes as additional gear as default.
(Reworked, just replicated the entry and put it back in to assault squad as a new file from the GST for "Power Weapons (Squad)")

Legion Rapier Battery -> not showing Quad Heavy Bolter weapon profile,
(Added Quad Heavy Bolter profile that was missing)

Pride of The Legion Rite of War -> Ebon Keshig not counting as compulsory troop choices
(Ebon Keshig are support unit, so can't be compulsory)

Blackshield Marauder Squads -> always showing in troop choices
(Can't currently fix, not sure what's wrong)

Alpha Legion Headhunter Kill Teams -> should lose their Infiltrate when they pick a rhino as a dedicated transport (unless this rule was changed somewhere)
(Fixed, Put script in to hide Infiltrate on the unit when they select either)

Alpha Legion Rewards of Treason -> General update and remove rules that are Legiones Astartes (X) and use Legiones Astartes (Alpha Legion)
(Not able to be done without a huge rewrite to in essence make new entries for every unit)

*Suggested Improvements:

Almost all Units -> Should already come with the Chainsword/Combat Blades that are present in its standard profile
(Honestly, i need a list of this. Part of the issue is that because of the ability to get chainaxes for World Eaters it messes stuff up. I think as far as i know there is no difference in Combat Blades and Chainswords. So they might be able to be combined into 1 entry properly.)

White Scars Kyzagan Assault Land Speeder -> I believe we can drop the "White Scars" and Just call it "Kyzagan Assault Land Speeder"
(As put higher up. Its the unit name)

The Ebon Keshig -> missing Max Grenade Harness & Max Power Glaive
-> shouldn't come with a grenade harness as default
->Should come with 5 power glaives as default
(Fixed Grenade Harness, but Power glaives is an issue due to formation of entry. The previous way it was done would have had you have to select every individual terminator 1 at a time in their own entry.) 

Headhunter Killteams -> Headhunters and Sargent should come with the combi weapon > combi bolter with banestrike rounds chosen as default
(Fixed)

Also Headhunter Prime Max power daggers to buy should be one (as he already has one as default and can buy one more)
(Fixed)

Assault Squads \ Jetbike Sky Hunter Squads \ Golden keshig: not coming with chainswords/CB as default
(Fixed with adding in an additional constraint)

Qin Xa missing Granade Harness weapon profile
(Fixed)

Qin Xa bodyguards can only have Tartaros armor, so maybe that should come pre selected
(Fixed)

Legion Glaive not coming with main gun equiped as default
(Fixed)

Xiphon Interceptor not coming with lascannnons as default
(Fixed)

Storm Eagle should come with Heavy bolter as pre selected wepon
(Fixed)

Legion Mastodon not showing its transport capacity and all its weapons are not pre selected
(Fixed)

And since I'm here, The Tactical Veteran Squads setup is awful, I think it would be much better if they were in the same scheme of Terminator Squads. where you can modify the gear of each individual.
(The issue is that for the mobile app, having it the way around the terminators are, takes about 5 mins to set up a unit as every model needs selecting individually. This is why it was changed in to the newer format (and it saved space)).

Blackshield Choices showing everywhere and ability to choose Blackshields in Legions & Allegiance not showing up

**Comment by Tomakokamikaze** [comment] 2019-11-26 12:01
Since this is still open:
Jetbike Sky Slayer Squad -> chainswords/CB not coming as default selection.

**Closed** 2019-12-01 18:43 UTC
