### ISSUE TITLE
Force weapon costs wrong for Librarian consul

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1167] opened 2017-11-02 15:24 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.07

**Platform:** Android

**Dropbox:** No

**Description:** You currently have the leagon preators artificor armor costing 10 points. It is default wargear and should be free. Additionally the libraian consol is being charged 20 points for his force weapon. It is also a free upgrade.

**Comment by capitaladot** [comment] 2017-11-02 15:26
@zopha sounds like a regression.

**Comment by zopha** [comment] 2017-11-02 18:44
I haven't touched the force weapon entry so I'm not sure whats causing that.

Cost for Artificer armour has been fixed and will be in the next release.

**Comment by capitaladot** [comment] 2017-11-02 18:53
Did you touch the bolt pistol or chainsword replace with lists, or likewise the power weapon or combibolter replace with lists, or the shared power weapon entry or shared force weapon entry? Changes to any of these could have broken this.

**Comment by zopha** [comment] 2017-11-02 18:57
This was highlighted in #1113 so looks like it has been an issue for awhile.

**Comment by Mayegelt** [comment] 2017-11-07 14:24
Also noticed that by selecting a Damocles Command Rhino that it says i have to many of them as max is 0

**Comment by HydraulicGold2** [comment] 2017-11-16 01:40
Similarly is that all Centurions in Terminator Armour seem to be charged 10pts for a Power Weapon under the may exchange Power Weapon for (Selection) list

**Comment by zopha** [comment] 2017-11-18 08:35
The force weapon was duplicated. The power weapon entry has force weapon options for thousand sons HQ units at 5 points for the upgrade. They'll only appear when Thounsand Sons are selected. If a Librarian is chosen there is a separate Force Weapon entry that has no cost.

Should be straightforward enough except for a Thousand Sons Librarian which would have both options visible.

**Closed** 2017-11-19 13:29 UTC
Labels: bug, Legion
