### ISSUE TITLE
Allied detachment with rite of war verification issue

### ISSUE THREAD

**Issue by Camyron** [BSData/horus-heresy#1555] opened 2019-07-17 18:04 UTC
If you bring a large army with a 1000+ allied detachment, that detachment can bring a master of the legion for that detachment, which allows for a rite of war for the allied detachment.
Currently, this is not allowed and you are told the roster has "1 too many selections from rite of war (max 1)".

**Comment by Camyron** [comment] 2019-07-17 18:05
https://github.com/BSData/horus-heresy/issues/740

**Comment by Mayegelt** [comment] 2019-08-13 11:32
Sorry it took so long to get around to this one. I think I've fixed it. Basically a whole bunch of the RoW entries had a limit of 1 per Roster, while a whole heap of other ones had 1 per Force. They should have all been set to 1 per Force.

**Comment by zopha** [comment] 2019-09-17 09:17
. It should be live for devices to update in 12-24 hours, depending on Appspot. I'll close this for now, if you get the updated file please test and reopen if the issue is still present.

**Closed by zopha** 2019-09-17 09:17 UTC
Labels: Bug - Validation, Legion
