### ISSUE TITLE
[Anon] Bug report: The Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#965] opened 2017-05-13 07:39 UTC
**File:** The Horus Heresy.gstz

**BattleScribe version:** 0.17.74

**Platform:** Windows

**Dropbox:** Yes

**Description:** Sekhmet Terminator Cabal don't show up in troops when you select The Guard of the Crimson King rite of War.

**Comment by zopha** [comment] 2017-05-13 13:37
Duplicate of #566

**Closed by zopha** 2017-05-13 13:37 UTC
Labels: bug, duplicate, Legion
