### ISSUE TITLE
[Anon] Bug report: (HH) Legiones Astartes - Crusade Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1228] opened 2018-01-21 01:00 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There seems to be a problem with the calculation of Terminator Legion Command squad points. A squad of 5 Terminators should be 75 (3 men) + 30 (2 extra men) + 75 (Terminator Armour worth 15 X 5) for a total of 180 points. When this is put into BattleScribe, it prices them at 190pts. Thanks.

**Comment by capitaladot** [comment] 2018-01-21 01:52
Thanks for the report. Will double check what the app is mathing.

**Comment by zopha** [comment] 2018-01-23 09:34
Duplicate of #1227

**Closed by zopha** 2018-01-23 09:34 UTC
Labels: Bug - Cost, Legion, Resolution - Duplicate
