### ISSUE TITLE
[Anon] Bug report: The Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1220] opened 2018-01-14 01:10 UTC
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Can't pick loyalist legions can't only pick traitor

**Comment by zopha** [comment] 2018-01-14 06:56
Duplicate of #1221

**Closed by zopha** 2018-01-14 06:56 UTC
Labels: Resolution - Duplicate
