### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3233] opened 2024-06-03 04:01 UTC
**File:** 2022 - LA - Thousand Sons.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Thousand Sons centurion and consul independent characters are no longer able to select a psychic discipline. The fix would be to re allow Thousand Sons consuls and centurions that do not already have a psychic discipline to be able to select one for +15 points, as per the Cult Arcana special rule.

**Comment by The4D6** [comment] 2024-06-03 13:05
Duplicate of #3230

**Closed by The4D6** 2024-06-03 13:05 UTC
