### ISSUE TITLE
[Anon] Bug report: 2022 - Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3240] opened 2024-06-04 20:04 UTC
**File:** 2022 - Horus Heresy.gstz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Legion Rapier Battery points are now incorrect. The base model is correct at 40 points, however each of the weapon upgrades are not. The Graviton Cannon is +20, not +60. The Laser Destroyer is +25, not +75. The Quad Launcher is +20, not +60.

**Comment by The4D6** [comment] 2024-06-06 09:56
Duplicate of #3213

**Closed by The4D6** 2024-06-06 09:56 UTC
