### ISSUE TITLE
Delegatus consul giving error on too many master of the legion

### ISSUE THREAD

**Issue by Grunanca** [BSData/horus-heresy#1924] opened 2021-05-30 09:59 UTC
Taking a delegatus in an army as general i get an error I have too many master of the legion 1 of maximum 0.

**Comment by Mayegelt** [comment] 2021-05-30 13:26
Hi ya.
I can't seem to get this one to reproduce.
Remember the Delegatus does have MOTL because he has the Right of Command rule. But can be taken in an army sized 1-999pts bypassing the min restriction. So if you set the army size or have stuff equal to 1000+pts then it will take the MOTL slot.

**Comment by Grunanca** [comment] 2021-05-30 19:39
Hey! I noticed now the warning only comes under 1.000 points. As soon as I pass that, it goes away🙂 I was 800 points into a 2k list when I saw it.Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 30.05.2021  15.26  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
Hi ya.
I can't seem to get this one to reproduce.
Remember the Delegatus does have MOTL because he has the Right of Command rule. But can be taken in an army sized 1-999pts bypassing the min restriction. So if you set the army size or have stuff equal to 1000+pts then it will take the MOTL slot.

**Comment by Mayegelt** [comment] 2021-05-31 00:28
> Hey! I noticed now the warning only comes under 1.000 points. As soon as I pass that, it goes away🙂 I was 800 points into a 2k list when I saw it.Sendt fra min Galaxy -------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 30.05.2021 15.26 (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) Hi ya. I can't seem to get this one to reproduce. Remember the Delegatus does have MOTL because he has the Right of Command rule. But can be taken in an army sized 1-999pts bypassing the min restriction. So if you set the army size or have stuff equal to 1000+pts then it will take the MOTL slot. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Any chance of posting the list in here? I can't seem to get it to replicate.
Are you by any chance setting your army list size to 1k? or are you leaving that section blank?

**Comment by Grunanca** [comment] 2021-05-31 04:34
Sure🙂Pic of error is attached++  Crusade (Legiones Astartes: Age of Darkness Army List) [770pts] +++ HQ +Damocles Command Rhino [100pts]Delegatus [65pts]: Bolt Pistol, On Foot, Power Armour (Centurion/Consul). Chainsword or Combat Blade: Chainswords/Combat Blades. Consul. . Delegatus+ Elites +Apothecarion Detachment [60pts]: Cult Arcana: Raptora (Telekinesis). Apothecary, Legion: Artificer Armour, Augury Scanner. . Chainsword or Combat Blade: Chainswords/Combat BladesDestroyer Squad, Legion [345pts]: Cult Arcana: Raptora (Telekinesis), 9x Destroyer Space Marine, Legion, Hardened Armour, Missile Launcher with Suspensor Web and Rad Missiles & Psyk-out Missiles, Missile Launcher with Suspensor Web and Rad Missiles & Psyk-out Missiles, Psyk-out Grenades. Destroyer Sergeant, Legion: Artificer Armour, Phosphex Bombs. . Chainsword or Combat Blade: Chainswords/Combat Blades. Terrax Pattern Termite Assault Drill (DT): 2x Twin-linked Bolter+ Troops +Veteran Tactical Squad, Legion [100pts]: 4x Bolt Pistol, 4x Bolter, 4x Chainswords/Combat Blades, 4x Veteran Space Marines, Legion. Veteran Sergeant, Legion: Bolt Pistol, Bolter. . Chainsword or Combat Blade: Chainswords/Combat BladesVeteran Tactical Squad, Legion [100pts]: 4x Bolt Pistol, 4x Bolter, 4x Chainswords/Combat Blades, 4x Veteran Space Marines, Legion. Veteran Sergeant, Legion: Bolt Pistol, Bolter. . Chainsword or Combat Blade: Chainswords/Combat Blades+ Fast Attack +Terrax Pattern Termite Assault Drill UnitTerrax Pattern Termite Assault Drill Unit+ Allegiance +Legion and Allegiance:   XV: Thousand Sons, TraitorRite of War: Chosen Duty+ Use Playtest Rules +Use Playtest Rules Errata 1.0 (From FAQ 1.1 Feb/2019): Playtest Rules Errata 1.0 On+ Warlord Traits +Warlord Traits+ Dedicated Transport Restictions +Dedicated Transports Restrictions: Dedicated transports are part of the parent unit++ Total: [770pts] ++Created with BattleScribe (https://battlescribe.net)Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 31.05.2021  02.29  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 



Hey! I noticed now the warning only comes under 1.000 points. As soon as I pass that, it goes away🙂 I was 800 points into a 2k list when I saw it.Sendt fra min Galaxy -------- Oprindelig besked --------Fra: Mayegelt @.> Dato: 30.05.2021 15.26 (GMT+01:00) Til: BSData/horus-heresy @.> Cc: Grunanca @.>, Author @.> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) Hi ya. I can't seem to get this one to reproduce. Remember the Delegatus does have MOTL because he has the Right of Command rule. But can be taken in an army sized 1-999pts bypassing the min restriction. So if you set the army size or have stuff equal to 1000+pts then it will take the MOTL slot. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



Any chance of posting the list in here? I can't seem to get it to replicate.

Are you by any chance setting your army list size to 1k? or are you leaving that section blank?

**Comment by Mayegelt** [comment] 2021-05-31 06:28
Seems like no picture attached.
I can see a few issues that would flag in this, but not the one you speak of. The delegatus needs Warlord and also needs a cult and a psychic mastery level.

**Comment by Grunanca** [comment] 2021-05-31 06:38
Trying again. Should be attached.Yeah, the list was not near finished, just had that warning before, and as I was reporting the rest I wanted to include it.Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 31.05.2021  08.28  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
Seems like no picture attached.
I can see a few issues that would flag in this, but not the one you speak of. The delegatus needs Warlord and also needs a cult and a psychic mastery level.

**Comment by Mayegelt** [comment] 2021-05-31 07:32
Still can't reproduce. But it might be that something is fixed on my end and not yours somehow.
Might be worth trying remove and redownload and see if that fixes it. It can be a case that for some reason an artefact can remain from a previous build and messes things up.
I've just uploaded a new release. If you download in the new way then you should have access to v15.0.3 Lots of little legion fixes Legion V634. If you download through Appspot then it will take anything up to a day. Let me know if you still get the error.

**Comment by Grunanca** [comment] 2021-05-31 07:47
Thanks for the fast fixes. Definitely motivates me to keep looking for stuff🙂 I'm checking the update tomorrow, can see I can only get the 15.0.2 right now from where I get my files.ErikSendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 31.05.2021  09.33  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
Still can't reproduce. But it might be that something is fixed on my end and not yours somehow.
Might be worth trying remove and redownload and see if that fixes it. It can be a case that for some reason an artefact can remain from a previous build and messes things up.
I've just uploaded a new release. If you download in the new way then you should have access to v15.0.3 Lots of little legion fixes Legion V634. If you download through Appspot then it will take anything up to a day. Let me know if you still get the error.

**Comment by Mayegelt** [comment] 2021-05-31 07:48
I try to fix when I can. Been ill recently (still am) so it has been slow going at times.

**Comment by Grunanca** [comment] 2021-05-31 07:52
No rush... Hope you get better soon! Wishing the best🙂Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 31.05.2021  09.49  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
I try to fix when I can. Been ill recently (still am) so it has been slow going at times.

**Comment by Mayegelt** [comment] 2021-05-31 20:19
Working now?

**Comment by Grunanca** [comment] 2021-06-01 04:20
Yup, just made a list, all errors gone. But sub orbital strikewing in no longer available under low in crusade. It says its hidden. There is only the emperial bastion. Shouldnt it be full of low choices?Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 31.05.2021  22.19  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
Working now?

**Comment by Mayegelt** [comment] 2021-06-01 06:20
I am going to hazard a guess that your list has a Delegatus as your warlord? If so they have the rule.

Restrictions: A Legion Praetor or Lords of War choice may not be taken in a Primary Detachment with a Legion Delegatus as its Warlord

So because of that all the LoW get hidden.

**Comment by Grunanca** [comment] 2021-06-01 07:04
Ah thanks! Had missed that rule because it wasn't in the rite of war🙂 I'll keep my eyes open for anything else. We are just getting used to deamons here, so all the book 8 stuff is really getting looked through now.Btw I'm part of the Varangian heresy crew. We got quite a lot of units and stuff. Would it be possible to get it added like the mournival rules? It is kinda like that, just in Scandinavia, where pretty much all events run on those rules. (I can find the pdfs and send them)We also run the real time event in the Raltac software. There we got a special Raltac force organisation (7-9 events per year). Basically its 1 compulsory hq, 2 open3 elite open 1 compulsory troop and 2 open 2 fast open2 heavy openNo unit including dedicated transports may exceed 350 points.Would it be possible to get that added? Then people can make lists for our events without a long list of errors🙂ErikSendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 01.06.2021  08.20  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
I am going to hazard a guess that your list has a Delegatus as your warlord? If so they have the rule.
Restrictions: A Legion Praetor or Lords of War choice may not be taken in a Primary Detachment with a Legion Delegatus as its Warlord
So because of that all the LoW get hidden.

**Comment by Mayegelt** [comment] 2021-06-01 07:09
I've still got a while bunch of Mournival stuff to add. But in theory it is possible to add.
Do you only add units or do you also modify existing ones?

**Comment by Grunanca** [comment] 2021-06-01 07:37
We add a whole new rite of war and apart from that, unit rules are the same. We never touch existing units, as we want players to be able to play from their books.It's a bunch of new units for marines, solar and especially militia. Militia also gets a few new provenances. Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 01.06.2021  09.09  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
I've still got a while bunch of Mournival stuff to add. But in theory it is possible to add.
Do you only add units or do you also modify existing ones?

**Comment by Mayegelt** [comment] 2021-06-01 07:39
Would likely be easy to add the FoC and RoW.
The units take a bit longer.
Provinces take only a small time to do.

**Comment by Grunanca** [comment] 2021-06-01 07:54
The Raltac foc would make our lives sooo much easier, we got our next event 31th of July. We are currently looking through our rules and checking for spelling errors etc, so I'll send them to you when they are correct🙂 we got 2 events in October using them. However it's a lot, so no rush if it takes longer than that. We also allow all the mournival and 30kaus stuff, so would be nice if they can all be set to in at the same time. But I don't know if they actually correct unit stats? Because we don't use their faq, we got our own.Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Mayegelt ***@***.***> Dato: 01.06.2021  09.39  (GMT+01:00) Til: BSData/horus-heresy ***@***.***> Cc: Grunanca ***@***.***>, Author ***@***.***> Emne: Re: [BSData/horus-heresy] Delegatus consul giving error on too many master of the legion (#1924) 
Would likely be easy to add the FoC and RoW.
The units take a bit longer.
Provinces take only a small time to do.

**Comment by Mayegelt** [comment] 2021-06-02 17:20
Closing this ticket if you can make a new one with all the links then if/when I get time I may be able to get to it.
If the FoC is a main one I should be able to get that done without much fuss. RoW however can take a lot longer depending on how much interaction it has with units

**Closed** 2021-06-02 17:20 UTC
Labels: Bug - Validation, Resolution - Can't Reproduce
