### ISSUE TITLE
Legion Jetbike Sky Slayer Support Squadron missing. 

### ISSUE THREAD

**Issue by Commisar** [BSData/horus-heresy#509] opened 2016-11-11 20:28 UTC
The heavy support variant of the jetbikes from the latest red book, seems to be missing. Was in the old data file.

**Comment by DonMorr** [comment] 2016-11-20 15:11
Duplicate of #500

**Comment by zopha** [comment] 2017-01-02 23:00
Added in latest release. May need some more work but the unit is available now.

**Closed by zopha** 2017-01-02 23:00 UTC
