### ISSUE TITLE
In disgrace all are equal assault sgt

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3256] opened 2024-06-09 20:51 UTC
**File:** 2022 - BG - Blackshields.catz

**BattleScribe version:** 3.27.34

**Platform:** Android

**Dropbox:** Yes

**Description:** 1. The in disgrace all are equal oath says that in lieu of a hq model anything with the character unit sub type has to take an upgrade to a characteristic, but the assault squad you are unable to do this. For example I have tried to upgrade an assault squad sgt when it lets me upgrade a despoiler sgt on the same roster with the weapons of desperation oath also selected.
2. Weapons of desperation oath says you don't have to outfit every model the same in a unit but the despoiler and tacticals for example have to have the same for every model

**Comment by nstephenh** [comment] 2024-06-11 13:41
For #2 we have what we feared. The user hasn't looked under "with options"

**Comment by The4D6** [comment] 2024-09-04 16:03
Closing #3253 as it's a duplicate of this

**Closed** 2024-09-04 21:44 UTC
Labels: Bug - Text/Rule/Profile, LA - Blackshields
