### ISSUE TITLE
Despoiler Squads incorrectly have Support Squad

### ISSUE THREAD

**Issue by Morturg** [BSData/horus-heresy#3085] opened 2024-01-20 17:57 UTC
**Describe the bug**
Despoiler Squads incorrectly have Support Squad
v97

**Comment by The4D6** [comment] 2024-01-26 09:52
Fixed in PR.

Issue was caused by the rule (which should only be visible when the Inductii option is selected) being visible by default and then _hidden_ when you selected Inductii. Simple true/false switch.

**Closed** 2024-01-26 21:02 UTC
Labels: bug, LA - Library, Bug - Text/Rule/Profile
