### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Thousand Sons.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3237] opened 2024-06-03 12:04 UTC
**File:** 2022 - LA - Thousand Sons.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** The Thousand Sons consoles can no longer take the Prosperine Arcana upgrade which they should be able to.

**Comment by The4D6** [comment] 2024-06-03 13:05
Duplicate of #3230

**Closed by The4D6** 2024-06-03 13:05 UTC
