### ISSUE TITLE
[Anon] Bug report: The Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#320] opened 2016-07-01 14:42 UTC
**File:** The Horus Heresy.gstz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** The Force Type option is missing and I am unable to find Fulgrim.

**Comment by Millicant** [comment] 2016-07-01 23:36
Could you be a bit more specific?  I don't think the catalogue is broken right now...

**Comment by thestudent911** [comment] 2016-07-02 00:18
On the mobile app where you are making a new list, I have selected The Horus Heresy game system. Below when I go to select the Force Type there is nothing to select. Only the Catalogue can be changed. Also before that issue I haven't been able to find Fulgrim in the Horus Heresy. Can you point out where I can find him?

**Comment by Millicant** [comment] 2016-07-02 03:54
That is strange, I haven't been able to reproduce this.  Maybe just try deleting/re-downloading your data?

Fulgrim is a Lord of War, available when you have the Emperor's Children selected.

**Comment by thestudent911** [comment] 2016-07-02 04:14
So I tried to remove and readd the data the issue still exists. I have a screenshot of what I am showing on my side.

**Comment by thestudent911** [comment] 2016-07-02 04:16
So this is what I'm seeing on my side

**Comment by amis92** [comment] 2016-07-02 09:07
@thestudent911 unfortunately mail attachments don't work, you have to post the photo from browser.

**Comment by thestudent911** [comment] 2016-07-03 04:42
Here is a screenshot of what I'm seeing on my end.

![image](https://cloud.githubusercontent.com/assets/20250015/16543770/2646c2e8-40a6-11e6-8ab5-ed47dcd166a2.png)

**Comment by capitaladot** [comment] 2016-07-03 12:21
I can't reproduce this. Perhaps select "delete all data" and re-add the
repo?

**Comment by thestudent911** [comment] 2016-07-03 14:59
I did try that but the issue is still there. I also tried to remove and readd the app itself which didn't help either

**Comment by thestudent911** [comment] 2016-07-03 15:26
So i removed all of the lists, removed all of the data. Removed the app then readded it back in. But unfortunately The Horus Hersey is the only one that doesn't show the option change the force type

**Comment by thestudent911** [comment] 2016-07-04 00:21
Please close this ticket out. I have resolved the issue. Thank you for all your help.

**Closed** 2016-07-04 19:50 UTC
