### ISSUE TITLE
Fortifications and Sacrificial Offering Rite of War

### ISSUE THREAD

**Issue by smokescreentk421** [BSData/horus-heresy#619] opened 2016-12-21 05:12 UTC
I've been trying to fix this myself but can't figure out what is going on.

When you choose the Sacrificial Offering Rite of War 13 instances of "The Horus Heresy V42) - must have 1 more selections of Fortifications (minimum 1)" appear.

I tried adding my own fortifications copied from other repositories but not had much luck with finding where this problem is coming from.

**Comment by zopha** [comment] 2016-12-21 07:23
It's more than likely a side effect of how the Fortifications are added now (like the Primarchs) in the Force Organization slot on BS. Either it's working as intended and there's a Battlescribe bug that's preventing it from detecting that selection (Happens with Master of the Legion on Primarchs atm as well) or it needs more work.

For your files the best place to start would be the GST file and the Force Entries/Age of Darkness section. Screenshot
![2016-12-21 06_51_37-data editor 2 00 06 - warhammer 30 000 - the horus heresy](https://cloud.githubusercontent.com/assets/1666415/21380007/070b376c-c74a-11e6-80ad-e13f28abf754.png)

The Fortification Entry highlighted leads to this
![2016-12-21 06_53_29-data editor 2 00 06 - warhammer 30 000 - the horus heresy](https://cloud.githubusercontent.com/assets/1666415/21380044/49b65880-c74a-11e6-82bc-81e39bd2b29b.png)

Which has the Sacrificial offering rite restriction.

Since the roster editor doesn't have any Force types "Fortification", they're added under the Force Organisation Force Type now, that's more than likely the root. If you add a new Selection Entry and give it the category "Fortification" and then add that new entry in your roster editor it may help with the rite of war restriction. If that's something you've already tried let us know!

This could all be wrong of course :) things can get complicated with FW and their rites of war. A fix for this will be coming in #529 but that may take a while as it's basically an overhaul of the fortification system. I'll leave this open as it's a separate issue that should be tracked.

**Comment by zopha** [comment] 2017-02-16 11:09
Work is being carried out and some of the background work has been completed for fortifications. The force org update has removed the validation for fortifications on this Rite of War so we'll have to reimplement it once the fortifications are in and working.

**Comment by alphalas** [comment] 2017-04-03 13:29
rolled into #863

**Closed by alphalas** 2017-04-03 13:29 UTC
Labels: bug, Legion
