### ISSUE TITLE
[Anon] Bug report: 2022 - LA - Alpha Legion.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3243] opened 2024-06-06 09:43 UTC
**File:** 2022 - LA - Alpha Legion.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** v2.03.27.341 Pts incorrect for Rapier Battery upgrades. Way too high.

**Comment by The4D6** [comment] 2024-06-06 09:56
Duplicate of #3213

**Closed by The4D6** 2024-06-06 09:56 UTC
