### ISSUE TITLE
QA desired on latest Age of Darkness Army List push.

### ISSUE THREAD

**Issue by capitaladot** [BSData/horus-heresy#334] opened 2016-07-19 16:40 UTC
I've implemented points, FoC (e.g. Malcador), and most rules changes for the new Age of Darkness Army List, but I'd like to see people QA it and file what issues.
# **Please file bugs in separate issues from this post.**

**Comment by Gyem13** [comment] 2016-07-20 22:56
The shatter shell option for the Legion Rapier behave strangely and is incorrectly priced (should be like the splitter shell).
Great job otherwise.

**Comment by Millicant** [comment] 2016-07-21 02:50
Holy hell, nicely done.  That was quite a push today.  I'm QA'ing right now.  

Here's the real rub... you/we are going to have to re-do all that again in the 2.0a catalogues.

**Comment by Mayegelt** [comment] 2016-07-21 14:37
You haven't given the Malcador a unit type (I did the same thing with my quick update i did for myself and posted up on a topic originally)

**Comment by Mayegelt** [comment] 2016-07-21 14:42
@capitaladot the Malcador also comes with Heavy Bolter Sponsors for free, while you have a charge on your one, meaning it is 10pts over cost.

**Comment by capitaladot** [comment] 2016-07-21 14:43
Thanks @Mayegelt; fixed and released.
... and just saw the Heavy Bolter thing (and fixed it). Let me know when you're done reviewing the unit and I'll push another release.

**Comment by Mayegelt** [comment] 2016-07-21 15:24
@capitaladot
Primus Medicae may not take power fists.
Chaplins for Nightlords can have their Crozius Arcanum be a Chainglaive (according to Alan Blegh when asked, as it is a paid for upgrade to the character)
Rhino / Bastalisk / Medusa / Whirlwind / Land Raider Squadron / Predators / Vindicators / Sicaran / Venator / Spartan (and most other tanks but not all) Pintle Mounted Weapons changed in prices. Combi Weapon is now 5pts, Heavy Bolter/Flamer is 10pts
Whirlwind Scorpius can now have pintle mounted weapons at the same costs as above.
Medusa and Whirlwind need Hunter Killer points downed to 5pts rather than the old 10.
Land Raider Achilles in the Land Raider squad should start with the Quad Mortar by default.

Still needs Imperius Prime Redoubt & Imperial Castellum Stronghold.

War Machine Detachments now both have to be of the same Type (so no more mixing a Typhon and a Cerberus). Also this can be a Questoris Knight (so 1-2 of them as a war machine detachment (top of pg9)).
Also need to add Baneblade, Banehammer, Stormlord, Shadowsword, Stormsword, Macharius and variants, 
Crassus and variants, Marauder Bomber, Marauder Destroyer, Thunderbolt Heavy Fighter, Crusade Avenger Strike Fighter, Minotaur (see Taghmata Omnissiah army list),
When used in conjunction with this army list, these vehicles may be further modified by the following upgrades: 
Space Marine Crew (Super-heavy Tanks only): +15 points
Battle Servitor Control (Flyers only): +15 points. If taken as an option for a Sub-orbital Strike Wing, then all the Flyers in the wing must be so upgraded.

Any of which that have 8HP or less need to be added to the War Machine Detachment section as you can have 1-2 of them for 1 LoW choice.

That is a bit to get on with :) but i think i caught it all.

**Comment by capitaladot** [comment] 2016-07-21 16:21
I swore I already did the pintel change... but I think I must not have yet sorted out that there are now two lists of pintel costs: one for some superheavies, and one for the rest of the list.

**Comment by capitaladot** [comment] 2016-07-21 16:22
War Machine Detachment is now correctly one selection, up to two models.
I really don't want to do the "optional" additional LoW.

**Comment by capitaladot** [comment] 2016-07-21 16:23
Imperial Primus Redoubt & Imperial Castellum Stronghold have always been available as Fortifications. I did just notice that the Imperial Primus Redoubt is now a Lord of War/Formation, in addition to being limited to games 2500 points and above.

**Comment by Mayegelt** [comment] 2016-07-21 16:27
Fair enough, when it releases and i get a hold of it i will likely add them myself :)
Though the Knights thing isn't in the optional, it is in the "Updated" section.

**Comment by capitaladot** [comment] 2016-07-21 16:27
The Knights are now in, under War Machine Detachment.

**Comment by capitaladot** [comment] 2016-07-21 16:28
@Mayegelt if you submit a pull request from a forked branch with the optional LoW, I will gladly review it and merge it in.

**Comment by Mayegelt** [comment] 2016-07-21 16:30
Cooleo :) kinda new to this, so that sounded like gibberish :)
So how do I do that?

**Comment by capitaladot** [comment] 2016-07-21 16:39
See the button in the upper right that says "Fork" (on the desktop interface)? Click that.
Download the file you want as "raw" CAT from the fork, make your changes, increment the file version number (second line), upload your changes to the fork as a commit, then I'll walk you through the pull request thing.

**Comment by Mayegelt** [comment] 2016-07-21 16:44
Can't seem to open the "raw" Cat data...

**Comment by capitaladot** [comment] 2016-07-21 17:00
You'll want to "Save As" then "File: Load Catalogue" in Catalogue Editor.

**Comment by Mayegelt** [comment] 2016-07-21 17:04
If i do i get

Details:
net.battlescribe.a.c.e: (HH) Legiones Astartes - Age of Darkness Army List.cat was corrupted and has been deleted.
	at net.battlescribe.a.c.c.a(BattleScribe:76)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame.b(BattleScribe:1330)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame.r(BattleScribe:58)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame$15.actionPerformed(BattleScribe:1048)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

-------------------- Caused By --------------------

net.battlescribe.a.c.e: Data file is too old and is no longer supported (null)
	at net.battlescribe.a.c.b.e(BattleScribe:364)
	at net.battlescribe.a.c.a.a(BattleScribe:179)
	at net.battlescribe.a.c.c.a(BattleScribe:69)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame.b(BattleScribe:1330)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame.r(BattleScribe:58)
	at net.battlescribe.desktop.catalogueeditor.CatalogueEditorFrame$15.actionPerformed(BattleScribe:1048)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by capitaladot** [comment] 2016-07-21 17:10
Interesting... if you open the file in a text editor, what Revision number are you seeing? The current rev is now 131, so you might want to delete your fork and try again. I don't think I had a bad revision, but it has happened before, and I can confirm the current revision is working for me.

**Comment by capitaladot** [comment] 2016-07-21 17:23
Wait, you're not in the 2.0 Data Editor, are you?
-------------------- Caused By --------------------

net.battlescribe.a.c.e: Data file is too old and is no longer supported (null)

**Comment by Mayegelt** [comment] 2016-07-21 17:26
I'm using http://www.battlescribe.net/help-catalogueeditor.html

**Comment by cowomo404** [comment] 2016-07-21 17:28
I don't have my new red book yet - 
but was the option for a power first upgrade on the tactical support sergeant removed in the new book or is it missing in error?

**Comment by capitaladot** [comment] 2016-07-21 17:29
Sounds like a goof.

**Comment by capitaladot** [comment] 2016-07-21 17:36
Fixed now. Further reports in separate issues, please? :)

**Comment by cowomo404** [comment] 2016-07-21 17:53
For sure, won't be able to do real QA until i have the book. Mine is delivered tomorrow - but will be out of town until Monday :(

**Comment by zopha** [comment] 2017-01-20 11:46
This issue is quite old now (6 months+) and unfortunately refers to older files that have been replaced :( so I'm going to close this off.

**Closed by zopha** 2017-01-20 11:46 UTC
Labels: help wanted
