### ISSUE TITLE
[Anon] Bug report: The Horus Heresy.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1579] opened 2019-10-03 14:50 UTC
**File:** The Horus Heresy.gstz

**BattleScribe version:** 2.03.01

**Platform:** Windows

**Dropbox:** No

**Description:** When using Legion Astartes: Age of Darkness (Crusade) I get the following error:

Must have 1 more selections of Siege Breaker (Minimum 1)

This is after selecting Artillery Tank Squadron, Legion. Note I do NOT select Phosphex shells, this is just with stock Medusa.

Thanks

**Comment by Mayegelt** [comment] 2019-10-03 18:03
Can't seem to get the issue to reproduce on my phone or desktop.
I checked with quad mortars, Achilles raider and Medusa tanks. All of which have an interaction with Siege Breakers.
Are you playing Hammer of Olympia RoW by any chance? As that requires a Siege breaker or Warsmith.

**Comment by capitaladot** [comment] 2019-10-03 19:41
Is Khyr Vhalen missing Warsmith? The Rite requires that, but perhaps is
checking for the wrong thing?

**Comment by Mayegelt** [comment] 2019-10-03 20:27
Looks like he doesn't have it as compulsory and with servo arm by look of it, and he should.
So if you select them he becomes overcost.

**Comment by capitaladot** [comment] 2019-10-03 20:30
So, add those things, and modify them as zero cost when he takes them seems
to be the fix!

**Comment by Mayegelt** [comment] 2019-10-03 21:00
Yep I'm just fixing that now. Though still not known if that was the issue of the original poster :D Though was a found issue none the less.

**Comment by capitaladot** [comment] 2019-10-03 21:06
It was indeed; one of my local Michigan, US dudes!

**Comment by Mayegelt** [comment] 2019-10-03 21:07
Well pull request is up and looks fixed now

**Closed** 2019-10-10 02:36 UTC
