### ISSUE TITLE
[Anon] Bug report: (HH) Legiones Astartes - Crusade Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1872] opened 2021-01-26 21:59 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Something in my 3500 point list of Blood Angels is missing it’s data files, and because of this I can’t open the whole list. After I attempt to open the list, and then get the pop-up telling me that there are missing data files, if I hit continue the app just freezes.

**Comment by Mayegelt** [comment] 2021-01-27 08:21
If the army list worked recently, the problem is likely due to the changes that fixed one of the other rites of war, and forced a change to some tanks entries.
If the list hasn't been opened in a long time. One of the updates destroyed all lists, though that was well over a year ago.
On Android I know there is the option to quickview a list, thus shows the army as a text doc. I assume iPhone has the same option. If unable to open the list, unfortunately it may be that you will need to recreate it.
Another major overhaul is however coming soon and may do the same at that point.
For some of my own lists it has been a case that it gives me an error to say that there is a problem with the list and it crashes the list out but then trying to reopen the list again will force it through but obviously missing the entries that are no longer there, so will need to manually be re-added again.

**Closed** 2021-01-30 20:17 UTC
Labels: Problem - Battlescribe Bug, Resolution - Can't Reproduce
