### ISSUE TITLE
Wrong points for Anvillus Pattern Dreadclaw Drop Pod

### ISSUE THREAD

**Issue by Cappec** [BSData/horus-heresy#1816] opened 2020-10-16 09:21 UTC
Hey, I noticed that the Anvillus Pattern Dreadclaw Drop Pod is 100pts instead of 115pts. Someone added the Droppod changes from the FAQs?
https://whc-cdn.games-workshop.com/wp-content/uploads/2018/07/Horus-Heresy-Drop-Pods-Errata-v1.0.pdf

Thanks

**Comment by Mayegelt** [comment] 2020-10-16 13:45
Which unit was it that the cost was wrong for?
Or by any chance are you playing Sons of Horus. If so Sons of Horus get it cheaper from their legion.

**Comment by Cappec** [comment] 2020-10-16 13:47
Oh really? Yes I'm using the Dreadclaw from the Sons of Horus, thanks for the indication. Sorry for the "Issue" alert!

**Comment by Mayegelt** [comment] 2020-10-16 13:49
![IMG_20201016_144829](https://user-images.githubusercontent.com/20280410/96266577-b46a4b80-0fbe-11eb-9f63-b3959cead66f.jpg)

They also get to use them more than other legions

**Comment by Cappec** [comment] 2020-11-03 08:33
Sorry to bother again, but if you use this datasheet (of 100 point) you have less rules than the updated one.. for example is missing the Inertial Guidance System, and in the 100 points datasheet is forcing you to deploy the dreadclaw always in hovering when arriving from Deep Strike. Should be correct to always use the updated version? Or if I play sons of horus I have to use the "lite" version of the dreadclaw?

**Comment by Cappec** [comment] 2020-11-11 07:53
I forgot to reopen the issue, check my last comment with the screenshot.
Thanks

**Comment by Mayegelt** [comment] 2020-11-11 08:18
The generic profile of the drop pod has changed as per FAQ update. However as far as we have been told, the pts difference remains the same.
Though having a check it looks like the SoH one doesn't get the guidance system on there legion one, but the army list one did...
Personal opinion is the rules get upgraded to latest version of their rules (as per what the rulebook says). However I'm unsure if they should keep the lower cost, though previously when asked this had been confirmed as a legion perk, rather than a misprint.
The other difficulty if you completely import the latest version of the rules. is that they would also lose the ability to take certain Sons of Horus units, unless you have certain RoW.

**Comment by Cappec** [comment] 2020-11-11 08:45
Do you have any reference about the fact on the first sentence?

`The generic profile of the drop pod has changed as per FAQ update. However as far as we have been told, the pts difference remains the same.`

So, in case my opponent complain, I can refer to this? :)

**Comment by Mayegelt** [comment] 2020-11-11 10:33
Sadly it is just in person talks with various people such as Mr Bligh, Wylie & Malhotra, both from myself and others reporting it. However this becomes hearsay in the eyes of some.
If you think you opponent will argue just reserve the additional PTS in your list unspent I guess.
I could add an option to either reduce or increase the cost as a clicky. Or make a special Dreadclaws that is SoH only and costs less, but doesn't have the guidance system.

**Comment by Cappec** [comment] 2020-11-11 12:58
Now I have sent an email to the rules team (and got the automatic answer from Malhotra, as mentioned by you), then I will attach here the image as proof for future issues.

Thanks!

**Comment by Cappec** [comment] 2020-11-12 08:43
in the meanwhile, if doesn't take too much time, could you please add the checkbox to add the 15 points? In this way will help a lot in the points management.. :D

Thanks

**Comment by Cappec** [comment] 2020-11-12 11:21
Sorry to shot so many shots, but in a SoH army, if the dreadclaw is taken as Fast Attack, should cost 115pts, because you won't use the special dreadclaw as dedicated transport, but the one from the faqs.

**Comment by Mayegelt** [comment] 2020-11-12 13:01
Ok, So just had a play around. What I done is made a similar solution to the rift barb one here #1826 
I have taken away the blanket 100pts cost for SoH for Anvilus pods. Instead each of the listed options (Justaerin Terminator Squad, Legion Terminator Squad, Legion Dreadnought (Talon of 1 only), Legion Seeker Squad, Reaver Attack Squad & Legion Command Squads)
It selected once for the army it will revert the cost back to 115 on all.

![image](https://user-images.githubusercontent.com/20280410/98943205-0aabab00-24e7-11eb-8dd9-481cde0a5dec.png)

**Comment by Cappec** [comment] 2020-11-12 13:15
Thanks, is it possible to have the checkbox in the Dreadclaw Fast Attack Selection? Because right now is still 100pts, instead of 115.

**Comment by Mayegelt** [comment] 2020-11-12 20:58
That will be fixed when you download the new version when it goes live. Basically as said above I removed the default value for them for SoH of 100 and added the reduced cost to all the units instead, then had the tickbox on all those units to modify it. So all Dreadclaws for all other units will be 115 regardless.

**Closed by Mayegelt** 2020-11-12 20:58 UTC
