### ISSUE TITLE
When is the next planned update

### ISSUE THREAD

**Issue by bryankia** [BSData/horus-heresy#631] opened 2016-12-29 19:59 UTC
First off.  Thank you very much to the author who has done so much work on the file.

It has been a month sense the last update and there is a long list of things wrong with the current data file.  Is their an eta on when we will see some of these items fixed?  

On a side note where could I find out how to modifie the data file.  I would be more than happy to jump in and help the community out as the community has been very good to me.

Peace,
Bryan

**Comment by capitaladot** [comment] 2016-12-29 20:50
There has so far been no coordination of releases. The closest thing to it
was @millicant stating that he wished to be the only one working on the 2.x
file before its release due to its fragility and the problems with
BattleScribe files and merging in git (this is a BattleScribe problem I
have talked with Jon about due to the XML parser used). I honored this wish
and continued work on the 1.x files. My fixes and features were never back
ported.

There are many regressions (lost features and fixes) and bugs in the 2.x
file, not to mention many changes and refactors (however well-meaning) that
have confused users. There has been an exodus to QuarterMaster among iOS
users I know in the US (this is still the only game in town on Android) who
play the HH, and because of the perpetual-license-to-annual-license change.

I have moved in the last month and still do not have usable home internet
(DIAF, Xfinity).

I do not know why @millicant has been absent since the 2.x release, but I
think he must only rarely have time/interest to work on the project. It
goes without saying that his contribution makes up the lion's share,
however; anything I and others have done has simply been updates (new and
changed units/profiles, full text of profile rules, etc) and corrections.

As to working on it, there really isn't documentation, but the Gitter
channel for then 40k file is helpful and a good sounding board.

**Comment by MrRta1910** [comment] 2016-12-29 21:02
I would also like to help as I have a heap of free time coming up is there a way to edit the file via mobile or laptop as I have all the books sitting in front of me

**Comment by zopha** [comment] 2016-12-29 21:31
:+1: for gitter.

@MrRta1910 the data file editor is desktop only, no mobile editor yet. The best way to learn how BS works is just to open the file and poke around and get an idea of a few things, pick a unit and try to recreate the entry.

Once you get stuck on something ask on gitter, I'll try to answer on the heresy channel if I know but the other good channel is the 40k one. Forge world can make rules complicated and when you add rites of war with legion rules it gets even worse.

**Comment by zopha** [comment] 2017-01-20 11:24
I've had a look around and there's no file creation manual for Battlescribe :( It doesn't look like anyone is poolling their knowledge in to a wiki or anything like that, so at the moment, the only way to learn is by looking at current files and working backwards to figure out how they do certain things.

I'll close this off for now as releases are coming out again but if there are any more questions just ask!

**Closed** 2017-02-03 16:25 UTC
Labels: question
