### ISSUE TITLE
[Anon] No company standard on Command Squad

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3223] opened 2024-05-29 21:53 UTC
**File:** 2022 - LA - Space Wolves.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** No company standard option on Company Command Squad

**Comment by The4D6** [comment] 2024-06-06 09:57
Duplicate of #3239 (and that one is much better worded/formatted)

**Closed by The4D6** 2024-06-06 09:57 UTC
