### ISSUE TITLE
World Eater Berseker Option

### ISSUE THREAD

**Issue by twizted86** [BSData/horus-heresy#3271] opened 2024-06-19 14:45 UTC
The Berseker option is missing for all World Eater Praetors.

**Comment by nstephenh** [comment] 2024-06-24 13:26
Duplicate of #3250, which I've now re-opened.

**Comment by nstephenh** [comment] 2024-06-24 13:55
Confirmed it's a battlescribe only issue.
We recommend switching to new recruit. I'll see if we can fix it but I'm not sure exactly what the cause of the issue is (I assume something related to psyker)

**Comment by Mayegelt** [comment] 2024-06-24 18:14
I found the issue for World Eater Berserker not showing up for Preators.
It's because in Preator its using the "Unit" for what it is searching for. Though I think even that might be broken as for Blackshields I don't think that the things that give a preator the psyker thing actually give the psyker category anyway.
The fix would be to work out what things give psyker such as I think burning lore does. then choose to restrict it on that, in the same way as the centurion is restricted if it takes librarian and esoterist

**Comment by Mayegelt** [comment] 2024-08-08 22:16
Will be fixed in https://github.com/BSData/horus-heresy/pull/3302

**Closed** 2024-08-10 11:00 UTC
Labels: bug, Done (in PR) but not on Release Branch, Battlescribe Only
