### ISSUE TITLE
[Anon] Rapier pattery points

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3221] opened 2024-05-29 21:27 UTC
**File:** 2022 - LA - Space Wolves.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Rapier Batteries have an overcoated Laser Destroyer upgrade (75. Should be 25/each)

**Comment by nstephenh** [comment] 2024-05-30 13:46
Related or duplicate of https://github.com/BSData/horus-heresy/issues/3213 ?

**Comment by The4D6** [comment] 2024-05-31 22:56
Duplicate of 3213

**Closed by The4D6** 2024-05-31 22:56 UTC
