### ISSUE TITLE
Command squad errors.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#749] opened 2017-02-17 16:45 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** When including a command squad, and when selecting weapons for said squad (such as power weapon, lighting claw, etc) you will get an error message if you include more than one selection, currently meaning your entire command squad can only have one power weapon.

**Comment by zopha** [comment] 2017-02-17 17:44
Duplicate of #739

**Closed by zopha** 2017-02-17 17:44 UTC
Labels: bug, duplicate
