### ISSUE TITLE
Legiones Astartes - Crusade Army List - Will not open on Windows Battlescribe 2.01.03

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#1043] opened 2017-07-12 06:56 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** Legiones Astartes lists cannot be created or edited. Lists for other army lists (Imperial Milita, Mechanicum, Talons, etc.) are fine.

I select the Horus Heresy game system, give the list a name, set a points limit, select Legiones Astartes: Age of Darkness Army List v457 from the rosters and click OK. Nothing happens.

**Comment by Velonad** [comment] 2017-07-13 04:22
Same issue here running on Windows 10 Pro 64-bit.

Same battlescribe version and Legiones Astartes list version. Using dropbox to sync roosters.

**Comment by alphalas** [comment] 2017-07-13 04:28
make sure you're running the newest ver of BS; update data, making sure to check the delete existing data checkbox on the dialog. If you don't see the dialog, you're not on the newest BS build.

**Comment by Velonad** [comment] 2017-07-13 04:31
I did just those things and still get the same results.

Will try to see if wiping out all BS data everywhere and redownloading data will work.

**Comment by alphalas** [comment] 2017-07-13 04:33
Otherwise idk what to say; I can't duplicate on iOS or Win10, also using DB.

**Comment by Velonad** [comment] 2017-07-14 04:24
Wiping all BS data everywhere did not help either, will try full reinstall, plus reboot for good measure.

**Comment by capitaladot** [comment] 2017-07-14 05:30
Likewise using w10 and Dropbox and cannot reproduce.

**Comment by Velonad** [comment] 2017-07-14 13:42
[battlescribe_log_edited.txt](https://github.com/BSData/horus-heresy/files/1148540/battlescribe_log_edited.txt)

Added a log file from when trying to add a rosoter. First I try to add a HH Legiones Astartes rooster using the standard FoC (Age of Darkness). No progress past pushing the Okay button, BS freezing for about 10 seconds, and then nothing happens other than putting me back at where I was before pressing "okay".

Second one I did the same, but then I switched datafiles to the 8th Edition data and tried to add a BA flyer wing. Success, and I note that in the logs for the BA list it seems to progress past the following area:

>+++++++++++++++++++++
+++ Validate Data +++
++ Total Validate Data: 9
+++++++++++++++++++++

**Comment by zopha** [comment] 2017-07-14 14:59
I tested on Android and it's working, thought that would be it and then I tested on Windows 7, BS 2.01.03 and I'm seeing the same thing. The okay button stays pressed for about 10 seconds and then nothing happens. I'm able to remove the CAL choice and choose another army roster which then loads file.

Did we have this issue before and it was a Battlescribe bug? Or @Jonskichov would you have any advice on this error?

**Comment by capitaladot** [comment] 2017-07-14 21:01
This may be the most complicated datafile out there, with the most units, weird constraints, etc. That it exposes and edge case can't be that surprising.

**Comment by capitaladot** [comment] 2017-07-14 21:04
It should be noted that each of the force orgs are now duplicated per catalog (.cat) given that constraints targeting entries from a  catalog due to the limitation that BattleScribe does not allow modifiers or constraints on catalogs that are included in from the game system (.gst).

**Comment by xxdarkgodzillaxx** [comment] 2017-07-16 05:13
Same issue is happening on my iPhone for space marines, I can do the others though.

**Comment by zopha** [comment] 2017-07-16 18:01
I've gone back through the data files and found the following is working
https://github.com/BSData/horus-heresy/releases/tag/v8.4.7
Please use this one until I can figure out what is causing the issue. Just download the source file zip, browse to your Battlescribe data folder, delete all the catz and gstz files in it and copy the contents over. It should look like

![2017-07-16 18_48_13-horus-heresy-8 4 7](https://user-images.githubusercontent.com/1666415/28250075-3624e73e-6a59-11e7-9759-2d7e595511bd.png)

**Comment by Velonad** [comment] 2017-07-17 07:17
Can confirm that your posted workaround does indeed work for me as well running on newst battlescribe and in windows 10 environment. Thanks for that @zopha.

I wish you best of luck with your search for what causes this bug :)

**Comment by capitaladot** [comment] 2017-07-19 19:13
@Jonskichov any help here?

**Comment by capitaladot** [comment] 2017-07-20 07:01
Lots of discussion around this and some experiments by @zopha. No clear plan yet.

**Comment by xxdarkgodzillaxx** [comment] 2017-07-20 16:46
Anything for battlescribe phone app?

**Comment by xxdarkgodzillaxx** [comment] 2017-07-20 16:49
iPhone sorry, won't let me edit my post.

**Comment by VulkanXVIII** [comment] 2017-07-22 04:22
This is so frustrating, Im a mega noob altering files and stuff, can someone post a more detailed description of how to use Zopha's fix? I dont fully understand.

**Comment by VulkanXVIII** [comment] 2017-07-25 07:34
Hello? Can someone please clue me in to whats happening here? This great unfuckening hasn't changed anything for me, still experiencing the same issues....

**Comment by Velonad** [comment] 2017-07-25 08:50
@VulkanXVIII see these step-by-step instructions:

1. Download the zip package on this site: [https://github.com/BSData/horus-heresy/releases/tag/v8.4.7]

2. Find the location of your data files, see image below:
![image](https://user-images.githubusercontent.com/28618861/28562794-fbcfd054-7123-11e7-85b6-8f4dcf6f2be6.png) Navigate to the horus heresy folder (located here in your datafiles: \BattleScribe\data\Warhammer 30,000 - The Horus Heresy) and delete all the files in this folder.

3. Navigate to where you downloaded the zip file, and follow the instructions in the image below:
![image](https://user-images.githubusercontent.com/28618861/28563525-88a7dfe2-7126-11e7-9f49-d695adda5fe3.png)

Voilà, should have fixed it. Please note that if you update automatically you most likely will get two HH datasets, one of which won't work for Legiones Astartes. I haven't tested to see if the updating removes the workaround datafiles.

Also a tip for future enquiries, typing demands like a whining no-knowledge kid is a pretty good way to not get people to bother to help you. Words like "please" and "thanks in advance for your help" are helpful here. Think on that for a bit if you may be so kind.

**Comment by capitaladot** [comment] 2017-07-25 11:32
@vulkanxviii Java version? @zopha found that 32bit Java on Windows was giving him trouble.

**Comment by capitaladot** [comment] 2017-07-25 11:34
@velonad any relief with the new release?

**Comment by VulkanXVIII** [comment] 2017-07-26 16:33
Wouldn't considering that whining, but alright.

**Comment by VulkanXVIII** [comment] 2017-07-26 16:35
I appreciate the step by step though. I did get it working.

**Comment by capitaladot** [comment] 2017-07-26 17:06
Recommend updating to a more recent iOS device or better yet Android.

**Comment by capitaladot** [comment] 2017-07-26 17:24
I would like to close this. Can those of you using the workaround delete
all data, come back onto the main line release, and re-test?

**Comment by Velonad** [comment] 2017-07-26 18:55
@capitaladot I'll be able to check tomorrow, will follow your instructions and let you know asap :)

**Comment by capitaladot** [comment] 2017-07-26 19:02
Thanks, @velonad

**Comment by capitaladot** [comment] 2017-07-28 00:28
Closing due to absence of further reports.

**Closed by capitaladot** 2017-07-28 00:28 UTC
Labels: bug
