### ISSUE TITLE
[Anon] Bug report: (HH) Legiones Astartes - Crusade Army List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#622] opened 2016-12-23 03:44 UTC
**File:** (HH) Legiones Astartes - Crusade Army List.catz

**BattleScribe version:** 2.00.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Wrong point value for extra armour, any vehicles that can be upgraded to having extra armour do so for 5 points as of the most recent Legion Astartes Age of Darkness Army List book

**Comment by zopha** [comment] 2016-12-23 06:53
Duplicate of #564

**Closed by zopha** 2016-12-23 06:53 UTC
Labels: bug, duplicate
