### ISSUE TITLE
[Anon] Bug report: 2022 - LI - Custodes.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/horus-heresy#3231] opened 2024-06-02 20:35 UTC
**File:** 2022 - LI - Custodes.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** No primarch slot for custodes. Unable to add valdor

**Comment by The4D6** [comment] 2024-06-03 09:22
Duplicate of #3229

**Closed by The4D6** 2024-06-03 09:22 UTC
