### ISSUE TITLE
Using Raven Guard Decapitation Strike

### ISSUE THREAD

**Issue by darkestvisions** [BSData/horus-heresy#415] opened 2016-08-04 08:47 UTC
Trying to use the 'Decapitation Strike' Rite of War in a 2000pts loyalist Raven Guard list, with Strike Captain Alvarex Maun as the HQ.

I receive the following error;

"Legiones Astartes: Age of Darkness Army List (Age of Darkness) has 3 too many selections from May be upgraded to one of these Consul roles: (maximum -3)..."

There are no other HQ choices in the list when this error occurs.

**Comment by capitaladot** [comment] 2016-08-04 11:10
Please update. There was a bug a number of releases back that I can confirm is fixed (I play the same list).

**Comment by darkestvisions** [comment] 2016-08-04 11:14
I tried that - already using the latest iOS app, and removed and downloaded the data again, and created a new army list - same error unfortunately

**Comment by capitaladot** [comment] 2016-08-04 11:31
What version of the Age of Darkness Army List does Battlscribe report when you create the list? It should say 163.

**Comment by capitaladot** [comment] 2016-08-04 12:06
Weird... I cannot reproduce this on the Java (desktop) app or Android.
Are there specific steps (or an order to it) that produce the error, or does it crop up regardless of what order you make your selections in?

**Comment by darkestvisions** [comment] 2016-08-04 12:09
The order seems to make no difference, nor does the type of HQ I apply the RoW to. The error occurs as soon as I choose Decapitation Strike, and disappears as soon as I move it!

**Comment by capitaladot** [comment] 2016-08-04 13:01
I'd love to fix this if I could reproduce it... I wonder if this is just an iOS specific bug?

**Comment by capitaladot** [comment] 2016-08-04 22:24
Confirmed to be an iOS specific bug, and I believe @Jonskichov has ended bugfix support for BattleScribe 1.x. Expect this to be fixed on iOS once BS2 is released.

**Closed by capitaladot** 2016-08-04 22:24 UTC
Labels: bug, wontfix
